import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { Inter,Outfit } from "next/font/google";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "On Wheels",
  description: "Generated by create next app",
  icons: {
    icon: "logo.png", // Path to your favicon in the public folder
  },
};
const outfit = Outfit({ subsets: ["latin"] });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
   <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
         
          <NavBar />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
